name: Wowza Streaming Engine Caption Handlers
services:
    wse:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:4.9.4-trial
        platform: linux/amd64
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=enabled #enabled | disabled | remove to not change
            - LOG_LEVEL=INFO #DEBUG INFO WARN ERROR
            - SIMU_LIVE=disabled
        volumes:
#to persist the configurations between starts of Wowza Streaming Engine, uncomment the lines below:
#            - ./wse/applications:/usr/local/WowzaStreamingEngine/applications
#            - ./wse/conf:/usr/local/WowzaStreamingEngine/conf
#            - ./wse/content:/usr/local/WowzaStreamingEngine/content
#            - ./wse/logs:/usr/local/WowzaStreamingEngine/logs
#            - ./wse/transcoder:/usr/local/WowzaStreamingEngine/transcoder
            - ./conf:/usr/local/WowzaStreamingEngine/conf.addon
            - ./lib:/usr/local/WowzaStreamingEngine/lib.addon
        ports:
            - 8087:8087
            - 80:80
            - 443:443
            - 1935:1935
            - 6970-6999:6970-6999/udp
        depends_on:
            wowza_setup:
                condition: service_completed_successfully

    wowza_setup:
        image: wowza_setup:latest
        build:
            context: wowza_setup
        restart: "no"
        volumes:
            - ./lib:/wowza_setup/downloads

    whisper_server:
        hostname: whisper.server
        image: wowza/whisper_streaming:latest
        # runtime: nvidia
        # deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           capabilities: [gpu]
        #           count: 1
        environment:
            - MODEL=tiny.en # tiny.en, base.en, small.en, medium.en, large-v3, large-v3-turbo
            - LOG_LEVEL=INFO
            - MIN_CHUNK_SIZE=1
            - SOURCE_LANGUAGE=en
            - REPORT_LANGUAGES=en
            # - TRANSLATE_HOST=libretranslate.server
            # - TRANSLATE_PORT=5000
            # - USE_GPU=True
            # - FP16=true            
        ports:
            - 3000:3000
        volumes:
            - ./model_cache:/tmp

    # libretranslate_server:
    #     hostname: libretranslate.server
    #     image: libretranslate/libretranslate:latest
    #     # image: libretranslate/libretranslate:latest-cuda 
    #     environment:
    #         - LT_LOAD_ONLY=en,fr,es,de,ja
    #     ports:
    #         - 5001:5000
    #     volumes:
    #         - /tmp/libretranslate_models_cache:/home/libretranslate/.local


    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
            - WSE_HOST=http://wse.docker:8087
        ports:
            - 8088:8080
